CREATE TABLE IF NOT EXISTS public.discussions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  proposal_id BIGINT NOT NULL,
  user_id TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS discussions_proposal_idx ON public.discussions (proposal_id);
CREATE INDEX IF NOT EXISTS discussions_created_idx ON public.discussions (created_at);
ALTER TABLE public.discussions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "discussions_select_all" ON public.discussions FOR SELECT USING (true);
ALTER PUBLICATION supabase_realtime ADD TABLE public.discussions;