-- forum threads (proposals)
CREATE TABLE IF NOT EXISTS public.forum_threads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT NOT NULL,
  title TEXT NOT NULL,
  content TEXT DEFAULT '',
  user_id TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  upvotes INTEGER DEFAULT 0,
  downvotes INTEGER DEFAULT 0
);
CREATE INDEX IF NOT EXISTS forum_threads_event_idx ON public.forum_threads (event_id);
CREATE INDEX IF NOT EXISTS forum_threads_created_idx ON public.forum_threads (created_at);
ALTER TABLE public.forum_threads ENABLE ROW LEVEL SECURITY;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='forum_threads' AND polname='forum_threads_select_all'
  ) THEN
    CREATE POLICY "forum_threads_select_all" ON public.forum_threads FOR SELECT USING (true);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables WHERE pubname='supabase_realtime' AND schemaname='public' AND tablename='forum_threads'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.forum_threads;
  END IF;
END $$;

-- forum comments
CREATE TABLE IF NOT EXISTS public.forum_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  thread_id BIGINT NOT NULL,
  event_id BIGINT NOT NULL,
  user_id TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  upvotes INTEGER DEFAULT 0,
  downvotes INTEGER DEFAULT 0,
  parent_id BIGINT NULL
);
CREATE INDEX IF NOT EXISTS forum_comments_thread_idx ON public.forum_comments (thread_id);
CREATE INDEX IF NOT EXISTS forum_comments_event_idx ON public.forum_comments (event_id);
CREATE INDEX IF NOT EXISTS forum_comments_created_idx ON public.forum_comments (created_at);
ALTER TABLE public.forum_comments ENABLE ROW LEVEL SECURITY;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='forum_comments' AND polname='forum_comments_select_all'
  ) THEN
    CREATE POLICY "forum_comments_select_all" ON public.forum_comments FOR SELECT USING (true);
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables WHERE pubname='supabase_realtime' AND schemaname='public' AND tablename='forum_comments'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.forum_comments;
  END IF;
END $$;