-- 创建论坛投票记录表（幂等）
CREATE TABLE IF NOT EXISTS public.forum_votes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  event_id BIGINT NOT NULL,
  content_id BIGINT NOT NULL,
  content_type TEXT NOT NULL CHECK (content_type IN ('thread','comment')),
  vote_type TEXT NOT NULL CHECK (vote_type IN ('up','down')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (user_id, content_type, content_id)
);
CREATE INDEX IF NOT EXISTS forum_votes_user_event_idx ON public.forum_votes (user_id, event_id);