-- 删除现有的event_follows表（如果存在）
DROP TABLE IF EXISTS public.event_follows CASCADE;

-- 创建event_follows表
CREATE TABLE public.event_follows (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  event_id BIGINT NOT NULL REFERENCES public.predictions(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (user_id, event_id)
);

-- 启用行级安全策略
ALTER TABLE public.event_follows ENABLE ROW LEVEL SECURITY;

-- 创建策略允许所有操作（开发环境）
CREATE POLICY "Allow all operations on event_follows" ON public.event_follows
FOR ALL USING (true) WITH CHECK (true);