-- Create flags table
CREATE TABLE IF NOT EXISTS public.flags (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  deadline TIMESTAMPTZ NOT NULL,
  verification_type TEXT CHECK (verification_type IN ('self', 'witness')) DEFAULT 'self',
  witness_id TEXT, -- 可选：如果是 witness 模式，这里存好友的 user_id 或 wallet_address
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'pending_review', 'success', 'failed')),
  proof_image_url TEXT,
  proof_comment TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add indexes
CREATE INDEX IF NOT EXISTS flags_user_id_idx ON public.flags (user_id);
CREATE INDEX IF NOT EXISTS flags_status_idx ON public.flags (status);
CREATE INDEX IF NOT EXISTS flags_created_at_idx ON public.flags (created_at);

-- Enable RLS
ALTER TABLE public.flags ENABLE ROW LEVEL SECURITY;

-- Policies
-- 1. 允许用户查看所有公开的 flag (或者只看自己的，根据需求。这里假设公开以便社交，或者目前只允许自己看)
--    目前为了简单，允许 authenticated 用户读取所有，或者只允许自己读取。
--    既然是“个人 + 邀请”，那默认应该只能自己看 + 见证人看。但为了方便展示“热门Flag”，也可以公开。
--    这里先设置为：允许所有认证用户读取（为了后续社交扩展），但写入只能是自己。

CREATE POLICY "flags_select_all" ON public.flags FOR SELECT USING (true);

CREATE POLICY "flags_insert_own" ON public.flags FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "flags_update_own" ON public.flags FOR UPDATE TO authenticated USING (
  -- 简单起见，这里只校验是否登录，实际业务逻辑在 API 层控制 user_id 匹配
  true
);

-- Realtime
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'flags'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.flags;
  END IF;
END $$;
