-- Supabase数据库初始化脚本
-- 用于创建Foresight项目所需的表结构

-- 创建预测事件表
CREATE TABLE IF NOT EXISTS predictions (
  id SERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  category TEXT NOT NULL,
  deadline TIMESTAMP NOT NULL,
  min_stake REAL NOT NULL,
  criteria TEXT NOT NULL,
  image_url TEXT DEFAULT '',
  reference_url TEXT DEFAULT '',
  status TEXT DEFAULT 'active' CHECK(status IN ('active', 'completed', 'cancelled')),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 创建分类表
CREATE TABLE IF NOT EXISTS categories (
  id SERIAL PRIMARY KEY,
  name TEXT UNIQUE NOT NULL
);

-- 插入默认分类
INSERT INTO categories (name) VALUES 
  ('科技'),
  ('娱乐'),
  ('时政'),
  ('天气')
ON CONFLICT (name) DO NOTHING;





-- 创建热门事件表（用于trending页面）
CREATE TABLE IF NOT EXISTS trending_events (
  id SERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  category TEXT NOT NULL,
  image_url TEXT NOT NULL,
  followers_count INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 创建事件关注表
CREATE TABLE IF NOT EXISTS event_follows (
  id SERIAL PRIMARY KEY,
  event_id INTEGER NOT NULL,
  user_id TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(event_id, user_id)
);



-- 插入示例预测事件（不指定id，让序列自动生成）
INSERT INTO predictions (title, description, category, deadline, min_stake, criteria, reference_url, status) VALUES 
  (
    '比特币在2025年底是否突破10万美元？',
    '预测比特币价格在2025年12月31日前是否达到或超过10万美元',
    '科技',
    '2025-12-31 23:59:59',
    1,
    '根据CoinMarketCap官方数据，比特币价格在2025年12月31日23:59:59前达到或超过10万美元',
    'https://coinmarketcap.com/currencies/bitcoin/',
    'active'
  ),
  (
    '2024年全球平均气温是否创历史新高？',
    '预测2024年全球平均气温是否超过历史最高记录',
    '天气',
    '2024-12-31 23:59:59',
    1,
    '根据世界气象组织发布的2024年全球平均气温数据，是否超过2023年的记录',
    'https://public.wmo.int/',
    'active'
  );

-- 插入热门事件示例数据
INSERT INTO trending_events (title, description, category, image_url, followers_count) VALUES 
  (
    'AI技术突破预测',
    '预测2025年AI技术将迎来重大突破，可能改变人类生活方式',
    '科技',
    '/images/ai-tech.jpg',
    1250
  ),
  (
    '娱乐产业复苏',
    '预测2024年娱乐产业将完全复苏，票房收入创历史新高',
    '娱乐',
    '/images/entertainment.jpg',
    890
  ),
  (
    '气候变化政策',
    '预测各国将在2025年推出更严格的气候变化应对政策',
    '时政',
    '/images/climate.jpg',
    2100
  ),
  (
    '极端天气事件',
    '预测2024年全球极端天气事件频率将增加',
    '天气',
    '/images/weather.jpg',
    1560
  );

-- 创建索引以提高查询性能
CREATE INDEX IF NOT EXISTS idx_predictions_category ON predictions(category);
CREATE INDEX IF NOT EXISTS idx_predictions_status ON predictions(status);
CREATE INDEX IF NOT EXISTS idx_trending_events_category ON trending_events(category);


-- 迁移修复：移除可能存在的 event_follows.user_id 外键并确保唯一约束
ALTER TABLE public.event_follows DROP CONSTRAINT IF EXISTS event_follows_user_id_fkey;

-- 尝试删除所有针对 user_id 的外键约束（名称不确定）
DO $$
DECLARE
  r RECORD;
BEGIN
  FOR r IN
    SELECT tc.constraint_name
    FROM information_schema.table_constraints tc
    JOIN information_schema.key_column_usage kcu
      ON tc.constraint_name = kcu.constraint_name
     AND tc.table_schema = kcu.table_schema
    WHERE tc.table_schema = 'public'
      AND tc.table_name = 'event_follows'
      AND tc.constraint_type = 'FOREIGN KEY'
      AND kcu.column_name = 'user_id'
  LOOP
    EXECUTE format('ALTER TABLE public.event_follows DROP CONSTRAINT IF EXISTS %I;', r.constraint_name);
  END LOOP;
END
$$;

-- 将 user_id 统一为 TEXT 类型
ALTER TABLE public.event_follows ALTER COLUMN user_id TYPE TEXT;

-- 确保 (user_id, event_id) 唯一约束存在（使用唯一索引）
CREATE UNIQUE INDEX IF NOT EXISTS event_follows_user_id_event_id_key ON public.event_follows (user_id, event_id);

-- 论坛投票记录表：限制每个用户对同一内容仅投一次票
CREATE TABLE IF NOT EXISTS public.forum_votes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  event_id BIGINT NOT NULL,
  content_id BIGINT NOT NULL,
  content_type TEXT NOT NULL CHECK (content_type IN ('thread','comment')),
  vote_type TEXT NOT NULL CHECK (vote_type IN ('up','down')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (user_id, content_type, content_id)
);
CREATE INDEX IF NOT EXISTS forum_votes_user_event_idx ON public.forum_votes (user_id, event_id);

-- 讨论表
CREATE TABLE IF NOT EXISTS public.discussions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  proposal_id BIGINT NOT NULL,
  user_id TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS discussions_proposal_idx ON public.discussions (proposal_id);
CREATE INDEX IF NOT EXISTS discussions_created_idx ON public.discussions (created_at);
ALTER TABLE public.discussions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "discussions_select_all" ON public.discussions FOR SELECT USING (true);
-- 实时订阅发布
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'discussions'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.discussions;
  END IF;
END $$;

-- 论坛主题表（提案）
CREATE TABLE IF NOT EXISTS public.forum_threads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT NOT NULL,
  title TEXT NOT NULL,
  content TEXT DEFAULT '',
  user_id TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  upvotes INTEGER DEFAULT 0,
  downvotes INTEGER DEFAULT 0
);
CREATE INDEX IF NOT EXISTS forum_threads_event_idx ON public.forum_threads (event_id);
CREATE INDEX IF NOT EXISTS forum_threads_created_idx ON public.forum_threads (created_at);
ALTER TABLE public.forum_threads ENABLE ROW LEVEL SECURITY;
CREATE POLICY "forum_threads_select_all" ON public.forum_threads FOR SELECT USING (true);
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'forum_threads'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.forum_threads;
  END IF;
END $$;

-- 论坛评论表
CREATE TABLE IF NOT EXISTS public.forum_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  thread_id BIGINT NOT NULL,
  event_id BIGINT NOT NULL,
  user_id TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  upvotes INTEGER DEFAULT 0,
  downvotes INTEGER DEFAULT 0,
  parent_id BIGINT NULL
);
CREATE INDEX IF NOT EXISTS forum_comments_thread_idx ON public.forum_comments (thread_id);
CREATE INDEX IF NOT EXISTS forum_comments_event_idx ON public.forum_comments (event_id);
CREATE INDEX IF NOT EXISTS forum_comments_created_idx ON public.forum_comments (created_at);
ALTER TABLE public.forum_comments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "forum_comments_select_all" ON public.forum_comments FOR SELECT USING (true);
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'forum_comments'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.forum_comments;
  END IF;
END $$;

-- 订单表
CREATE TABLE IF NOT EXISTS public.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  verifying_contract TEXT NOT NULL,
  chain_id INTEGER NOT NULL,
  maker_address TEXT NOT NULL,
  maker_salt TEXT NOT NULL,
  outcome_index INTEGER NOT NULL,
  is_buy BOOLEAN NOT NULL,
  price TEXT NOT NULL,
  amount TEXT NOT NULL,
  remaining TEXT NOT NULL,
  expiry TIMESTAMPTZ NULL,
  signature TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'open',
  sequence BIGINT GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS orders_maker_salt_unique ON public.orders (verifying_contract, chain_id, maker_address, maker_salt);
CREATE INDEX IF NOT EXISTS orders_book_idx ON public.orders (verifying_contract, chain_id, outcome_index, is_buy, price);
CREATE INDEX IF NOT EXISTS orders_status_idx ON public.orders (status);
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
CREATE POLICY "orders_select_all" ON public.orders FOR SELECT USING (true);

-- 市场映射表
CREATE TABLE IF NOT EXISTS public.markets_map (
  event_id BIGINT NOT NULL,
  chain_id INTEGER NOT NULL,
  market TEXT NOT NULL,
  collateral_token TEXT DEFAULT '',
  tick_size NUMERIC DEFAULT 0,
  resolution_time TIMESTAMPTZ,
  status TEXT DEFAULT 'open',
  outcome_count INTEGER DEFAULT 2,
  outcomes JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (event_id, chain_id)
);
CREATE INDEX IF NOT EXISTS markets_map_market_idx ON public.markets_map (market);
ALTER TABLE public.markets_map ENABLE ROW LEVEL SECURITY;
CREATE POLICY "markets_map_select_all" ON public.markets_map FOR SELECT USING (true);

-- 创建预测事件选项表
CREATE TABLE IF NOT EXISTS public.prediction_outcomes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  prediction_id BIGINT NOT NULL REFERENCES public.predictions(id) ON DELETE CASCADE,
  outcome_index INTEGER NOT NULL,
  label TEXT NOT NULL,
  description TEXT,
  color TEXT,
  image_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(prediction_id, outcome_index)
);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_prediction_outcomes_prediction_id ON public.prediction_outcomes(prediction_id);

-- 启用 RLS
ALTER TABLE public.prediction_outcomes ENABLE ROW LEVEL SECURITY;

-- 允许所有用户读取
CREATE POLICY "prediction_outcomes_select_all" ON public.prediction_outcomes FOR SELECT USING (true);

-- 允许认证用户插入（API层需校验管理员权限）
CREATE POLICY "prediction_outcomes_insert_authenticated" ON public.prediction_outcomes FOR INSERT TO authenticated WITH CHECK (true);
